openapi: "3.0.3"
info:
  title: Users API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: Récupère la liste des utilisateurs
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/SizeParam'
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  name: "Alice"
                  email: "alice@example.com"
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Bad types for provided query parameters"
components:
  parameters:
    PageParam:
      name: page
      in: query
      description: Numéro de page (entier)
      required: false
      schema:
        type: integer
        minimum: 1
        example: 1
    SizeParam:
      name: size
      in: query
      description: Taille de page (entier)
      required: false
      schema:
        type: integer
        minimum: 1
        example: 20
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error