openapi: "3.0.3"
info:
  title: Tasks API
  version: "1.0.0"
paths:
  /tasks:
    get:
      summary: Retourne la liste des tâches
      responses:
        '200':
          description: Liste des tâches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
    post:
      summary: Crée une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TaskCreate'
            example:
              - title: "Acheter du lait"
                completed: false
              - title: "Appeler le plombier"
                completed: false
      responses:
        '201':
          description: Tâches créées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 2
                  title: "Acheter du lait"
                  completed: false
                - id: 3
                  title: "Appeler le plombier"
                  completed: false
    delete:
      summary: Supprime plusieurs tâches identifiées par une liste d'IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdList'
            example:
              - 1
              - 2
      responses:
        '200':
          description: Liste des tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retourne une tâche par ID
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Faire les courses"
                completed: false
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Task not found"
    delete:
      summary: Supprime une tâche par ID et retourne la tâche supprimée
      responses:
        '200':
          description: Tâche supprimée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Faire les courses"
                completed: false
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Task not found"
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - completed
    TaskCreate:
      type: object
      properties:
        title:
          type: string
        completed:
          type: boolean
      required:
        - title
    IdList:
      type: array
      items:
        type: integer
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message